function [DateTime, Time] = ImportData(filename)

    %% Import data from text file.
    % Script for importing data from the following text file:
    %
    %    C:\Users\ancal\Desktop\DNB_Data_cleaned\DataFull_20100423_30_AA.csv
    %
    % To extend the code to different selected data or a different text file,
    % generate a function instead of a script.

    % Auto-generated by MATLAB on 2017/12/03 18:49:56

    %% Initialize variables.
    % filename = 'C:\Users\ancal\Desktop\DNB_Data_cleaned\DataFull_20100423_30_AA.csv';
    delimiter = ',';

    %% Format string for each line of text:
    %   column1: text (%s)
    %	column2: text (%s)
    %   column3: text (%s)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%s%s%s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Allocate imported array to column variable names
    RIC = dataArray{:, 1};
    DateTime = dataArray{:, 2};
    Time = dataArray{:, 3};
DateTime(1,:) = [];
Time(1,:) = [];

    %% Clear temporary variables
    clearvars filename delimiter formatSpec fileID dataArray ans;


end